CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    is_banned BOOLEAN NOT NULL DEFAULT FALSE,
    is_vip BOOLEAN NOT NULL DEFAULT FALSE,
    is_calculate BOOLEAN NOT NULL DEFAULT FALSE,
    paid_until TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
