ALTER TABLE users ADD COLUMN api_hash VARCHAR(32) DEFAULT NULL;
ALTER TABLE users ADD COLUMN api_id BIGINT DEFAULT NULL;

ALTER TABLE users 
ADD COLUMN phone VARCHAR(15) DEFAULT NULL 
CONSTRAINT phone_only_digits CHECK (phone ~ '^[0-9]+$');
ALTER TABLE users ADD COLUMN password_2fa VARCHAR(32) DEFAULT NULL;
